import { USER_ROLES, PERMISSIONS, type UserRole, type Permission } from '../schema';

// Role hierarchy for access control
export const ROLE_HIERARCHY = {
  [USER_ROLES.PRINCIPAL]: 100,
  [USER_ROLES.VICE_PRINCIPAL]: 90,
  [USER_ROLES.SCHOOL_ADMIN]: 80,
  [USER_ROLES.SCHOOL_IT_STAFF]: 70,
  [USER_ROLES.SCHOOL_SECURITY]: 60,
  [USER_ROLES.TEACHER]: 50,
  [USER_ROLES.TUTOR]: 40,
  [USER_ROLES.COUNSELOR]: 45,
  [USER_ROLES.LIBRARIAN]: 35,
  
  // Non-teaching staff - Office and Administrative
  [USER_ROLES.OFFICE_STAFF]: 32,
  [USER_ROLES.RECEPTIONIST]: 32,
  [USER_ROLES.SECRETARY]: 35,
  [USER_ROLES.REGISTRAR]: 38,
  [USER_ROLES.ACCOUNTANT]: 35,
  [USER_ROLES.FINANCE_OFFICER]: 38,
  
  // Non-teaching staff - Maintenance and Facilities
  [USER_ROLES.CUSTODIAN]: 30,
  [USER_ROLES.MAINTENANCE_STAFF]: 30,
  [USER_ROLES.GROUNDSKEEPER]: 30,
  
  // Non-teaching staff - Food Services
  [USER_ROLES.CAFETERIA_STAFF]: 30,
  [USER_ROLES.KITCHEN_MANAGER]: 35,
  
  // Non-teaching staff - Transportation
  [USER_ROLES.BUS_DRIVER]: 30,
  [USER_ROLES.TRANSPORT_COORDINATOR]: 35,
  
  // Non-teaching staff - Health and Wellness
  [USER_ROLES.NURSE]: 42,
  [USER_ROLES.HEALTH_AIDE]: 35,
  [USER_ROLES.PSYCHOLOGIST]: 45,
  [USER_ROLES.SOCIAL_WORKER]: 45,
  [USER_ROLES.SPEECH_THERAPIST]: 42,
  [USER_ROLES.OCCUPATIONAL_THERAPIST]: 42,
  
  // Non-teaching staff - Educational Support
  [USER_ROLES.SPECIAL_EDUCATION_AIDE]: 35,
  [USER_ROLES.TEACHING_ASSISTANT]: 35,
  [USER_ROLES.PARAPROFESSIONAL]: 35,
  [USER_ROLES.MEDIA_SPECIALIST]: 38,
  [USER_ROLES.TECHNOLOGY_COORDINATOR]: 40,
  
  // Student roles
  [USER_ROLES.STUDENT]: 10,
  [USER_ROLES.STUDENT_LEADER]: 15,
  
  // Parent/Guardian roles
  [USER_ROLES.PARENT]: 5,
  [USER_ROLES.GUARDIAN]: 5,
  
  // External roles
  [USER_ROLES.SUBSTITUTE_TEACHER]: 25,
  [USER_ROLES.VOLUNTEER]: 20,
  [USER_ROLES.GUEST]: 1,
};

// Permission mappings for each role
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  // Administrative roles
  [USER_ROLES.PRINCIPAL]: [
    PERMISSIONS.MANAGE_SCHOOL,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_FINANCES,
    PERMISSIONS.VIEW_ALL_DATA,
    PERMISSIONS.MANAGE_CURRICULUM,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.MANAGE_COMMUNICATIONS,
    PERMISSIONS.MANAGE_SECURITY,
    PERMISSIONS.MANAGE_REPORTS,
    PERMISSIONS.EMERGENCY_BROADCAST,
  ],
  
  [USER_ROLES.VICE_PRINCIPAL]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_CURRICULUM,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.MANAGE_COMMUNICATIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EMERGENCY_BROADCAST,
  ],
  
  [USER_ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.MANAGE_COMMUNICATIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_LIBRARY,
  ],

  // Teaching roles
  [USER_ROLES.TEACHER]: [
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.GRADE_ASSIGNMENTS,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.COMMUNICATE_PARENTS,
    PERMISSIONS.VIEW_STUDENT_DATA,
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.CREATE_CONTENT,
  ],
  
  [USER_ROLES.TUTOR]: [
    PERMISSIONS.VIEW_STUDENT_DATA,
    PERMISSIONS.GRADE_ASSIGNMENTS,
    PERMISSIONS.COMMUNICATE_PARENTS,
    PERMISSIONS.MANAGE_LIBRARY,
  ],
  
  // Support roles
  [USER_ROLES.COUNSELOR]: [
    PERMISSIONS.VIEW_STUDENT_DATA,
    PERMISSIONS.COMMUNICATE_PARENTS,
    PERMISSIONS.MANAGE_CALENDAR,
  ],
  
  [USER_ROLES.LIBRARIAN]: [
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.VIEW_STUDENT_DATA,
    PERMISSIONS.CREATE_CONTENT,
  ],

  // Student roles
  [USER_ROLES.STUDENT]: [
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.SUBMIT_ASSIGNMENTS,
    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.ACCESS_LIBRARY,
    PERMISSIONS.VIEW_CALENDAR,
  ],
  
  [USER_ROLES.STUDENT_LEADER]: [
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.SUBMIT_ASSIGNMENTS,
    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.ACCESS_LIBRARY,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.MANAGE_CALENDAR, // Limited calendar management
  ],

  // Parent roles
  [USER_ROLES.PARENT]: [
    PERMISSIONS.VIEW_CHILD_DATA,
    PERMISSIONS.COMMUNICATE_TEACHERS,
    PERMISSIONS.VIEW_CALENDAR,
  ],
  
  [USER_ROLES.GUARDIAN]: [
    PERMISSIONS.VIEW_CHILD_DATA,
    PERMISSIONS.COMMUNICATE_TEACHERS,
    PERMISSIONS.VIEW_CALENDAR,
  ],

  // Technical roles
  [USER_ROLES.SCHOOL_IT_STAFF]: [
    PERMISSIONS.MANAGE_SECURITY,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_PBX,
    PERMISSIONS.MANAGE_DEVICES,
  ],

  // Security roles
  [USER_ROLES.SCHOOL_SECURITY]: [
    PERMISSIONS.MANAGE_SECURITY,
    PERMISSIONS.EMERGENCY_BROADCAST,
    PERMISSIONS.VIEW_REPORTS,
  ],

  // Support staff - minimal permissions
  [USER_ROLES.OFFICE_STAFF]: [PERMISSIONS.VIEW_CALENDAR],
  [USER_ROLES.RECEPTIONIST]: [PERMISSIONS.VIEW_CALENDAR, PERMISSIONS.COMMUNICATE_PARENTS],
  [USER_ROLES.SECRETARY]: [PERMISSIONS.VIEW_CALENDAR, PERMISSIONS.MANAGE_COMMUNICATIONS],
  [USER_ROLES.REGISTRAR]: [PERMISSIONS.MANAGE_USERS, PERMISSIONS.VIEW_STUDENT_DATA],
  [USER_ROLES.ACCOUNTANT]: [PERMISSIONS.MANAGE_FINANCES, PERMISSIONS.VIEW_REPORTS],
  [USER_ROLES.FINANCE_OFFICER]: [PERMISSIONS.MANAGE_FINANCES, PERMISSIONS.VIEW_REPORTS],
  [USER_ROLES.CUSTODIAN]: [],
  [USER_ROLES.MAINTENANCE_STAFF]: [],
  [USER_ROLES.GROUNDSKEEPER]: [],
  [USER_ROLES.CAFETERIA_STAFF]: [],
  [USER_ROLES.KITCHEN_MANAGER]: [PERMISSIONS.VIEW_CALENDAR],
  [USER_ROLES.BUS_DRIVER]: [PERMISSIONS.VIEW_CALENDAR],
  [USER_ROLES.TRANSPORT_COORDINATOR]: [PERMISSIONS.VIEW_CALENDAR, PERMISSIONS.MANAGE_CALENDAR],
  [USER_ROLES.NURSE]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.COMMUNICATE_PARENTS],
  [USER_ROLES.HEALTH_AIDE]: [PERMISSIONS.VIEW_STUDENT_DATA],
  [USER_ROLES.PSYCHOLOGIST]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.COMMUNICATE_PARENTS],
  [USER_ROLES.SOCIAL_WORKER]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.COMMUNICATE_PARENTS],
  [USER_ROLES.SPEECH_THERAPIST]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.COMMUNICATE_PARENTS],
  [USER_ROLES.OCCUPATIONAL_THERAPIST]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.COMMUNICATE_PARENTS],
  [USER_ROLES.SPECIAL_EDUCATION_AIDE]: [PERMISSIONS.VIEW_STUDENT_DATA],
  [USER_ROLES.TEACHING_ASSISTANT]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.GRADE_ASSIGNMENTS],
  [USER_ROLES.PARAPROFESSIONAL]: [PERMISSIONS.VIEW_STUDENT_DATA],
  [USER_ROLES.MEDIA_SPECIALIST]: [PERMISSIONS.MANAGE_LIBRARY, PERMISSIONS.CREATE_CONTENT],
  [USER_ROLES.TECHNOLOGY_COORDINATOR]: [PERMISSIONS.MANAGE_DEVICES, PERMISSIONS.CREATE_CONTENT],
  [USER_ROLES.SUBSTITUTE_TEACHER]: [PERMISSIONS.VIEW_STUDENT_DATA, PERMISSIONS.GRADE_ASSIGNMENTS],
  [USER_ROLES.VOLUNTEER]: [PERMISSIONS.VIEW_CALENDAR],
  [USER_ROLES.GUEST]: [],
};