// User role definitions
export const USER_ROLES = {
  // Student roles by education level
  STUDENT_ELEMENTARY: "student_elementary",
  STUDENT_MIDDLE: "student_middle", 
  STUDENT_HIGH: "student_high",
  STUDENT_COLLEGE: "student_college",
  
  // Educational staff
  TEACHER: "teacher",
  TUTOR: "tutor",
  PRINCIPAL: "principal",
  VICE_PRINCIPAL: "vice_principal",
  COUNSELOR: "counselor",
  LIBRARIAN: "librarian",
  
  // Administrative staff
  SCHOOL_ADMIN: "school_admin",
  SCHOOL_SECURITY: "school_security",
  SCHOOL_IT_STAFF: "school_it_staff",
  IT_STAFF: "it_staff",
  SECURITY_STAFF: "security_staff",
  
  // Parent/Guardian roles
  PARENT: "parent",
  GUARDIAN: "guardian",
  
  // System roles
  SUPER_ADMIN: "super_admin",
  SYSTEM_ADMIN: "system_admin",
  CONTENT_MODERATOR: "content_moderator",
  SUPPORT_STAFF: "support_staff",
} as const;

export type UserRole = typeof USER_ROLES[keyof typeof USER_ROLES];

// Permission definitions
export const PERMISSIONS = {
  // Content permissions
  CONTENT_CREATE: "content:create",
  CONTENT_READ: "content:read",
  CONTENT_UPDATE: "content:update",
  CONTENT_DELETE: "content:delete",
  CONTENT_PUBLISH: "content:publish",
  
  // User management permissions
  USER_CREATE: "user:create",
  USER_READ: "user:read",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_MANAGE_ROLES: "user:manage_roles",
  
  // Course/Class management
  COURSE_CREATE: "course:create",
  COURSE_READ: "course:read",
  COURSE_UPDATE: "course:update",
  COURSE_DELETE: "course:delete",
  COURSE_ENROLL: "course:enroll",
  
  // Assignment permissions
  ASSIGNMENT_CREATE: "assignment:create",
  ASSIGNMENT_READ: "assignment:read",
  ASSIGNMENT_UPDATE: "assignment:update",
  ASSIGNMENT_DELETE: "assignment:delete",
  ASSIGNMENT_SUBMIT: "assignment:submit",
  ASSIGNMENT_GRADE: "assignment:grade",
  
  // Library permissions
  LIBRARY_READ: "library:read",
  LIBRARY_UPLOAD: "library:upload",
  LIBRARY_DELETE: "library:delete",
  LIBRARY_MODERATE: "library:moderate",
  
  // Analytics permissions
  ANALYTICS_VIEW_OWN: "analytics:view_own",
  ANALYTICS_VIEW_CLASS: "analytics:view_class",
  ANALYTICS_VIEW_SCHOOL: "analytics:view_school",
  ANALYTICS_VIEW_ALL: "analytics:view_all",
  
  // Communication permissions
  COMMUNICATION_SEND: "communication:send",
  COMMUNICATION_BROADCAST: "communication:broadcast",
  COMMUNICATION_MODERATE: "communication:moderate",
  
  // System permissions
  SYSTEM_ADMIN: "system:admin",
  SYSTEM_SETTINGS: "system:settings",
  SYSTEM_BACKUP: "system:backup",
  SYSTEM_LOGS: "system:logs",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role-Permission mappings
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [USER_ROLES.STUDENT_ELEMENTARY]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_OWN,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.STUDENT_MIDDLE]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_OWN,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.STUDENT_HIGH]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_UPLOAD,
    PERMISSIONS.ANALYTICS_VIEW_OWN,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.STUDENT_COLLEGE]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_UPLOAD,
    PERMISSIONS.ANALYTICS_VIEW_OWN,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.TEACHER]: [
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_UPDATE,
    PERMISSIONS.ASSIGNMENT_DELETE,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_UPDATE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_UPLOAD,
    PERMISSIONS.ANALYTICS_VIEW_CLASS,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_BROADCAST,
  ],
  
  [USER_ROLES.PRINCIPAL]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_MODERATE,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.COMMUNICATION_BROADCAST,
    PERMISSIONS.COMMUNICATION_MODERATE,
  ],
  
  [USER_ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_MANAGE_ROLES,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_MODERATE,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.COMMUNICATION_BROADCAST,
    PERMISSIONS.COMMUNICATION_MODERATE,
  ],
  
  [USER_ROLES.PARENT]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_OWN,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.GUARDIAN]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_OWN,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  [USER_ROLES.SYSTEM_ADMIN]: [
    PERMISSIONS.SYSTEM_ADMIN,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_BACKUP,
    PERMISSIONS.SYSTEM_LOGS,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_MANAGE_ROLES,
    PERMISSIONS.ANALYTICS_VIEW_ALL,
  ],
  
  // Add other roles with their respective permissions
  [USER_ROLES.TUTOR]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_CLASS,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.VICE_PRINCIPAL]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_SCHOOL,
    PERMISSIONS.COMMUNICATION_BROADCAST,
  ],
  
  [USER_ROLES.COUNSELOR]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.ANALYTICS_VIEW_CLASS,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.LIBRARIAN]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_UPLOAD,
    PERMISSIONS.LIBRARY_DELETE,
    PERMISSIONS.LIBRARY_MODERATE,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.SCHOOL_SECURITY]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.SCHOOL_IT_STAFF]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_BACKUP,
    PERMISSIONS.COMMUNICATION_SEND,
  ],
  
  [USER_ROLES.IT_STAFF]: [
    PERMISSIONS.SYSTEM_ADMIN,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_BACKUP,
    PERMISSIONS.SYSTEM_LOGS,
    PERMISSIONS.USER_READ,
    PERMISSIONS.ANALYTICS_VIEW_ALL,
  ],
  
  [USER_ROLES.SECURITY_STAFF]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.COMMUNICATION_MODERATE,
    PERMISSIONS.SYSTEM_LOGS,
  ],
  
  [USER_ROLES.CONTENT_MODERATOR]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.LIBRARY_MODERATE,
    PERMISSIONS.COMMUNICATION_MODERATE,
  ],
  
  [USER_ROLES.SUPPORT_STAFF]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.SYSTEM_LOGS,
  ],
};